services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: p@ssWord
      MYSQL_DATABASE: crop
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - d:/docker-data/mysql:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci